### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by fwenzel** [bigboringsystem/bigboringsystem#106]
Call me old-skool, but a text-based system of posts should probably have an RSS feed. So one can follow it in a feed reader. Or digest it and do something fun with it.

**Comment by axelav** [comment]
@fwenzel would this just be a public feed, ie http://bigboringsystem.com/discover?

also, do you want to work on this? if not I'd like to give it a go.

**Comment by fwenzel** [comment]
Go right ahead, I could work on this but probably won't have enough time soon enough.

Also, I was thinking about a public feed for discover, but a per-person feed probably makes a lot of sense too. Likely, the code overhead for both instead of just one is minute!

**Comment by coleGillespie** [comment]
see closed pull request above for example. needs tests to validate, worked for me locally. cannot get to creating tests until later

**Comment by coleGillespie** [comment]
done

**Comment by ednapiranha** [comment]
https://github.com/bigboringsystem/bigboringsystem/commit/66edcc7f19eaf2395f1785ce29964a9845ffa4b7
