### ISSUE TITLE
Is there a way to change the timezone for posts?

### ISSUE THREAD

**Issue by Charlotteis** [bigboringsystem/bigboringsystem#109]
Hey bbs folk,
Just wondering if there is away to change the timezone each person is working in?
I just posted something and it displayed 11.20am but it was 19:20 here in the UK :)

Thanks!

**Comment by k88hudson** [comment]
+1 to `moment`, although `moment.timezone` should not be necessary to convert to the reader's local time as long as times are stored as UTC and formatted on the client.

i.e. `moment.format(post.time)` should be enough.

**Comment by ednapiranha** [comment]
https://github.com/bigboringsystem/bigboringsystem/commit/7cd356ac3b30e5471572d541d48681693a4a5c9e
