### ISSUE TITLE
Error page should render actual error response text

### ISSUE THREAD

**Issue by k88hudson** [bigboringsystem/bigboringsystem#114]
Currently it does not:

![image](https://cloud.githubusercontent.com/assets/1455535/5621275/f77a869e-9501-11e4-9d7a-e064fb58a9e5.png)

It would be nice to at least have something in the console for debugging

**Comment by pvenkatakrishnan** [comment]
same for me. debugging this now. i have correctly updated uid, and all twilio details on my `local.json` per readme...

**Comment by k88hudson** [comment]
Ah! I think I know why -- I'm hitting this on `/post`, except my patch returns an error response from that path instead of redirecting to an error page. heh

**Comment by pvenkatakrishnan** [comment]
just updating. i figured my problem as well  (which was unrelated to @k88hudson issue) , in case you want to close this out.
Looks like mine was a problem in updating the `uid` correctly and hence errored in `profile.getByUID(op, function (err, user) { ..}`
