### ISSUE TITLE
Adhere to linting + add linting to CI

### ISSUE THREAD

**Issue by TheAlphaNerd** [bigboringsystem/bigboringsystem#117]
Should linting be adding to CI to assure specific rules such as quotations, white space, etc etc etc are followed?

**Comment by jasonrhodes** [comment]
I thought we had a linter called @ednapiranha ?

**Comment by TheAlphaNerd** [comment]
lololol  Exactly what prompted this

I’m just in the process of cleaning up all the linting across the repo and making the linter be run as part of CI… PR coming soon=
