### ISSUE TITLE
in reply to any url

### ISSUE THREAD

**Issue by coleGillespie** [bigboringsystem/bigboringsystem#122]
I am not sure this is even an issue, i kind of like the feature of sharing a link that is not actually part of bbs but as you can see I was able to post http://bigboringsystem.com/post/post!1420513218-e1 in reply to a non bbs post. 

Issue or working as designed?

**Comment by jasonrhodes** [comment]
I've found this to be a really nice little feature of the open reply box. I say keep it as-is.

**Comment by coleGillespie** [comment]
cool, closing
