### ISSUE TITLE
Reply notifications

### ISSUE THREAD

**Issue by coleGillespie** [bigboringsystem/bigboringsystem#123]
Would be nice if users could have a way of being notified if someone has replied to one of their posts. This way the conversation could continue. Maybe a conversations page?

**Comment by coleGillespie** [comment]
maybe the posts page could show replies?

**Comment by isaacs** [comment]
Duplicate of #61 and #35.  Partly addressed by #138.  A page that just shows all replies to all of your posts would be interesting.
