### ISSUE TITLE
bundle css restricting view area

### ISSUE THREAD

**Issue by coleGillespie** [bigboringsystem/bigboringsystem#132]
Maybe it is just me but viewing on a desktop leaves the .content class at max-width: 408px; this feels restricted. Would be nice if the view area was more responsive to the current viewing environment.

**Comment by imakewebthings** [comment]
We don't want a completely fluid width for posts. Long line length is bad for readability, so some max is a good thing. Current max-width puts our line length at 51 characters. If we take 45-75 characters per line as generally acceptable for easily scanned line-length, it's on the low side but acceptable. CSS masters @llkats and @fox, do you have any opinions on this?

**Comment by coleGillespie** [comment]
just an idea, feel free to reject

**Comment by jasonrhodes** [comment]
I'm pretty sure this will all get solved with the CSS work planned in #1, so if you're interested in this, follow along with that ticket and jump in to help wherever you can!

**Comment by thefoxis** [comment]
Yeah, we will make it a little bit less constrained but having good reading experience in mind. No worries. Before that we want to modularise CSS (#129).
