### ISSUE TITLE
Deleted post URLs should 404

### ISSUE THREAD

**Issue by jasonrhodes** [bigboringsystem/bigboringsystem#139]
Clicking on a deleted post URL right now looks like it's returning a 500

http://cl.ly/image/1K3g1u2t3C05

It should be 404 page not found

**Comment by isaacs** [comment]
+1

**Comment by coleGillespie** [comment]
@jasonrhodes to me it looks like it is actually returning a 200. in the route logic it is set to return a 404 with the error wrapped in a Boom class.

```javascript
exports.get = function (request, reply) {
  // redirect /post/user!<uid>!<postid> to /post/post!<postid>
  var key = request.params.key;
  var keyparts = key.split('!');
  var postid = keyparts.pop();
  if (keyparts.length !== 1 || keyparts[0] !== 'post') {
    return reply.redirect('/post/post!' + postid).permanent();
  }

  db.get('post!' + postid, function (err, post) {
    if (err) {
      return reply(Boom.wrap(err, 404));
    }

    post.created = setDate(post.created);

    getReplyPosts(post, function (err, replies) {
      if (err) {
        return reply(Boom.wrap(err, 404));
      }

      post.replies = replies;
      replies.forEach(function (reply) {
        reply.created = setDate(reply.created);
      });

      reply.view('post', {
        analytics: conf.get('analytics'),
        id: request.params.key,
        session: request.session.get('uid') || false,
        op: request.session.get('op'),
        post: post
      });
    });
  });
};
```

**Comment by jasonrhodes** [comment]
The error page will always return 200 because it successfully loaded, but 404 should always be caught and display 'page not found'. The custom error message shown there means it probably returned a 500 error, but I need to look into it further to be sure.

**Comment by coleGillespie** [comment]
@jasonrhodes the error being returning when i log it is as follows:

```
[NotFoundError: Key not found in database [post!1420651214-fe]]
```

This means we probably just need to pass in a string or whatever message we want to display

**Comment by jasonrhodes** [comment]
No, we just want to have it return a 404 in the system so our 404 error handler catches it.

**Comment by coleGillespie** [comment]
@jasonrhodes line 298 in index.js route logic is giving the message that we pass it instead of the ctx.reason that we create in switch above. message already exists in most cases and ctx.reason is the fallback. it needs to be the opposite.

```javascript
  if (ctx.reason) {
    // Use actual message if supplied
    ctx.reason = message || ctx.reason;
    return reply.view('error', ctx);
  } else {
    ctx.reason = message.replace(/\s/gi, '+');
    reply.redirect(request.path + '?err=' + ctx.reason);
  }
```

needs to be

```javascript
  if (ctx.reason) {
    // Use actual message if supplied
    ctx.reason = ctx.reason || message;
    return reply.view('error', ctx);
  } else {
    ctx.reason = message.replace(/\s/gi, '+');
    reply.redirect(request.path + '?err=' + ctx.reason);
  }
```

**Comment by jasonrhodes** [comment]
Yeah this is from a change made in a PR the other day. We do want to make sure that it logs that message if in dev mode still, but yeah the printed message in the error view should be more generic.

**Comment by coleGillespie** [comment]
So, the 404 handler is not working correctly then?

**Comment by jasonrhodes** [comment]
Yeah it's already in there doing that, just need to make sure it's working. It checks: `if (process.env.npm_lifecycle_event === 'dev')` 

I think I can knock this out pretty easily in a little while because I reviewed the ticket that introduced this behavior. Thanks for helping me narrow it down!

**Comment by coleGillespie** [comment]
@jasonrhodes still need help on this one?

**Comment by isaacs** [comment]
So, really, the bug here is "Error pages should return the specified error codes".

We're passing a 404 in there, but it looks like it doesn't actually set the response code.
