### ISSUE TITLE
app crash on initial clone

### ISSUE THREAD

**Issue by coleGillespie** [bigboringsystem/bigboringsystem#145]
anyone else seeing this with a fresh install from master?
![screen shot 2015-01-07 at 4 17 04 pm](https://cloud.githubusercontent.com/assets/745064/5653534/0880e7a2-9689-11e4-8475-a68cec7c7fdb.png)

**Comment by coleGillespie** [comment]
gulp version 3.8.10

**Comment by TheAlphaNerd** [comment]
I’m seeing it too… They just updated gulp-nodemon as well which is causing weirdness

**Comment by jasonrhodes** [comment]
@coleGillespie what version of gulp-nodemon do you have? `npm list gulp-nodemon` should tell you...

**Comment by coleGillespie** [comment]
![screen shot 2015-01-07 at 5 55 40 pm](https://cloud.githubusercontent.com/assets/745064/5654956/78190a6a-9696-11e4-9bd1-1785a641280a.png)

**Comment by jasonrhodes** [comment]
Ok that's the latest so they haven't updated it to remove the bad nodemon upgrade yet.

**Comment by TheAlphaNerd** [comment]
I don’t think there is a bad nodemon update… since the last published version was 6 months ago

Seems to me like the gulp-nodemon folks just published a borked version=

**Comment by coleGillespie** [comment]
something changed recently in one of the gulp deps, not sure what yet

**Comment by jasonrhodes** [comment]
@TheAlphaNerd see https://github.com/JacksonGariety/gulp-nodemon/issues/49

Looks like nodemon 1.3.0-x auto updated early in the latest gulp-nodemon release for some reason.

**Comment by coleGillespie** [comment]
#145
