### ISSUE TITLE
Nodemon and gulp-nodemon dependency issue breaks npm start

### ISSUE THREAD

**Issue by jasonrhodes** [bigboringsystem/bigboringsystem#146]
The problem in #145 is a nodemon and gulp-nodemon dependency problem, see: JacksonGariety/gulp-nodemon/issues/49

Looks like gulp-nodemon might have fixed the problem so if you `npm update gulp-nodemon` it may be solved? If not we should just lock to an earlier version of gulp-nodemon for now.

**Comment by TheAlphaNerd** [comment]
I vote that this is a reason to land #74 early. Thoughts?

**Comment by jasonrhodes** [comment]
Will that fix? Looks like the problem is at least partially with nodemon, which seems to drop whatever is in 'npm start' as the executable to run your script (instead of node)...

**Comment by TheAlphaNerd** [comment]
you can try the branch... works perfectly for me

**Comment by TheAlphaNerd** [comment]
As mentioned in the previous thread... nodemon has not been published in 6 months... I have been using nodemon this way without issue for quite a bit

**Comment by coleGillespie** [comment]
he did push some updates in the past 6 hours

**Comment by jasonrhodes** [comment]
Except that Remy is obviously working on some pre release version that leaked out for the gulp-nodemon package, it seems? I'm not 100% sure but I think locking down to 1.0.4 of gulp-nodemon is the easiest, safest fix for now.

**Comment by TheAlphaNerd** [comment]
Yeah looks to me like gulp-nodemon actually started tracking a version that isn't stable

**Comment by TheAlphaNerd** [comment]
If I just do ```npm install nodemon``` you get version 1.2.1

**Comment by coleGillespie** [comment]
@jasonrhodes what do you mean by locking down to 1.0.4 when i fresh install it is still broken for me locally

**Comment by coleGillespie** [comment]
@jasonrhodes this can be closed now

**Comment by jasonrhodes** [comment]
Closed by #146
