### ISSUE TITLE
Should bold/italics be allowed?

### ISSUE THREAD

**Issue by fwenzel** [bigboringsystem/bigboringsystem#153]
Fundamental question, perhaps. As a mostly-text system, should BBS allow ``*italic*`` and ``**bold**`` text?

I think it'd allow some level of expression in the posts, without going quite too crazy, similar to how twitter @-names are autolinked, and general URLs are linked as well.

**Comment by imakewebthings** [comment]
My vote is nay. Besides the slippery slope of formatting and the fun of explaining Markdown to users, I enjoy the way plaintext forces users to create their own forms of emphasis (or as it is, revert to Usenet standards.)

**Comment by jasonrhodes** [comment]
I also vote "nay" for the same reasons. Monospace ASCII don't need no
formattin.

**Comment by fwenzel** [comment]
Fair enough; should auto-linking also go away?

**Comment by isaacs** [comment]
We auto-link using the Twitter library.  This makes it easy for people to refer to each other, and for hyperlinks to be clickable.  (The #hashtag handling is a bit weird, though, admittedly.)

This is a only-slightly-hyper text medium.  No formatting.
