### ISSUE TITLE
Name field is overescaped

### ISSUE THREAD

**Issue by fwenzel** [bigboringsystem/bigboringsystem#154]
STR:

Edit your profile and change your name to: ``~HELLO~``

Note the tildes turn into ``&#x7e;``

**Comment by rtorr** [comment]
@fwenzel We are using this lib https://github.com/hapijs/hoek in reaction to some abuse yesterday. Looks like you can config it a bit to allow more characters.

Line in question https://github.com/bigboringsystem/bigboringsystem/blob/master/lib/profile.js#L29

**Comment by fwenzel** [comment]
It's fine if you escape that character, just don't overdo it (i.e., don't render the entity name, literally)

**Comment by imakewebthings** [comment]
This isn't even just a matter of display, it's a bug. If you go to your profile and change your name to ~~ and save you will see the escaped text. If you save again, you get each of *those* characters escaped. It's escaping all the way down. Creating a pull to fix this in a few minutes.

**Comment by imakewebthings** [comment]
Fix landed in #169.
