### ISSUE TITLE
Is there any reason not to hash phone numbers when we store them?

### ISSUE THREAD

**Issue by jasonrhodes** [bigboringsystem/bigboringsystem#167]
Would be a nice privacy sell and doesn't seem like it would affect any of the ways we use the number if we just hash it after Twilio use but before db save, but I am far from an expert on crypto security stuff so I could be missing any number of things.

**Comment by ednapiranha** [comment]
We can do one-way hashing of numbers but you would need to run a migration on user accounts and reset their session to update. There might be some other checks to make.

**Comment by imakewebthings** [comment]
You would also need to salt. A lookup table of every possible phone number is way too easy to generate.

**Comment by ednapiranha** [comment]
well it's open for a fixin! :) any takers? :)

**Comment by TheAlphaNerd** [comment]
I'm definitely interested in helping out with this one.  I am curious how to properly salt the hashes if the entire code base is public.

**Comment by TheAlphaNerd** [comment]
I am also not entirely sure the best way to approach migrating the current DB, although I guess a one off script can probably do it.

**Comment by ednapiranha** [comment]
yeah one off script is fine. lotsa tests to write to verify ;)

**Comment by jasonrhodes** [comment]
Keep the salt value in local.json

**Comment by TheAlphaNerd** [comment]
Smart cookie!

**Comment by ednapiranha** [comment]
https://github.com/bigboringsystem/bigboringsystem/commit/f4d9d8194399465ba5c3bf9279a257528970b13e
