### ISSUE TITLE
Security vulnerability disclosure

### ISSUE THREAD

**Issue by remixz** [bigboringsystem/bigboringsystem#188]
While finding vulnerabilities may be rare in a program like this, due to its simplicity, it still can happen, and there should be an appropriate way to report them. Even if it's just an email of one of the maintainers that someone can send a bug to, that'd be great.

I bring this up since I found a bug in chat that allows for arbitrary HTML to be sent to anyone connected, and I've made a patch as well, but I don't want to PR it without warning since someone could take advantage of it while not fixed.

**Comment by jasonrhodes** [comment]
Good idea, @remixz -- for now you can hit me up at rhodesjason on freenode if you want to discuss.
