### ISSUE TITLE
Double escaping in chat usernames

### ISSUE THREAD

**Issue by jasonrhodes** [bigboringsystem/bigboringsystem#190]
Right now we use hoek to escape usernames when we save them, and then we escape the names again on the socket 'user' event to prevent malicious events emitted from a browser that could contain HTML and JS etc. This fixes a security issue for us, but it means that for usernames that are pulled from the database, they are getting double-escaped in the chat user list.

Should we unescape the usernames in the database and only escape them on display? I have no idea what the best practice is here, I seem to remember something about filter input, escape output, but I honestly don't even know exactly what that means. :P  

cc: @remixz @rtorr @imakewebthings

**Comment by remixz** [comment]
With https://github.com/bigboringsystem/bigboringsystem/pull/189, we actually shouldn't have to escape the names in chat anymore, since it's from the session now, and they're escaped when saved to the database as you said. I'll fix that in the PR now.

**Comment by jasonrhodes** [comment]
@imakewebthings whenever you have a chance, if you can take a look at #189 and see what you think?

**Comment by ednapiranha** [comment]
oops merged in @remixz 's fix already - seems to be working?

**Comment by jasonrhodes** [comment]
\o/ hooray, then! :+1: 

Nice work, @remixz -- thanks.
