### ISSUE TITLE
export is only page 1

### ISSUE THREAD

**Issue by isaacs** [bigboringsystem/bigboringsystem#191]
Is there any way to export more than just the first page of posts?

Maybe we need like a ?page=... query or something?

**Comment by imakewebthings** [comment]
@isaacs Maybe I don't follow, but I can't reproduce this locally. When I export `.json` I see all 32 of my (local) posts. Do I need more to hit this?

**Comment by isaacs** [comment]
Ah, weird... seems like it is working as intended.
