### ISSUE TITLE
Bug with highlighting nick and @twitter name rendering 

### ISSUE THREAD

**Issue by ednapiranha** [bigboringsystem/bigboringsystem#210]

**Comment by ednapiranha** [comment]
@llkats something for you to look at maybe? :dancer:

**Comment by llkats** [comment]
🍺🍺🍺🍺🍺🍺🍺🍺🍺🍺🍺🍺🍺

**Comment by ednapiranha** [comment]
https://github.com/bigboringsystem/bigboringsystem/commit/8622798ec02ce86da277e45ffc02eb0c82902b03 fixed!
