### ISSUE TITLE
npm install failures

### ISSUE THREAD

**Issue by lucasgonze** [bigboringsystem/bigboringsystem#232]
```
$npm install
npm WARN deprecated jade@1.8.2: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm ERR! git rev-list -n1 7bc13e1b566a9ac2a717a2b6f9cc188855277fdf: fatal: bad object 7bc13e1b566a9ac2a717a2b6f9cc188855277fdf
```

The Jade thing is simple enough, and is only a WARN, but I thought it was worth letting you know.

Thoughts on the rev-list ERR?

**Comment by lucasgonze** [comment]
Debug log

[npm-debug.log.txt](https://github.com/bigboringsystem/bigboringsystem/files/493846/npm-debug.log.txt)

**Comment by ednapiranha** [comment]
Sorry about that! This project more or less stopped getting updates and I ended up rewriting over here https://github.com/revolting/bbs (this one should have the correct pug updates among other stuff)
