### ISSUE TITLE
username notifications

### ISSUE THREAD

**Issue by llkats** [bigboringsystem/bigboringsystem#39]
Experiment with notifying chatroom users when their names are mentioned in chat.

Potentially would only apply to users currently in the chat area, but nowhere else on the site.

Maybe also highlight usernames when they are mentioned in the text of the chat.

**Comment by llkats** [comment]
So a first pass for username highlighting is here: c0ec4c0df2850febcc0c9f9533776a25cd0d4fd7 and it looks like this:

![https://dl.dropboxusercontent.com/u/37968874/img/bbs-username-highlight-pink.png](https://dl.dropboxusercontent.com/u/37968874/img/bbs-username-highlight-pink.png)

If anyone has any thoughts, I'm all ears. Will try to work on a favicon notifying thinger tomorrow.

**Comment by thefoxis** [comment]
@llkats&mdash;I think it's good, although if we ever do color coding for nicknames (one color per nick) then this might be problematic to notice. We could do a very subtle background on the entire line with an animation to fade after x seconds (so it's not a rainbow) or just keep this for now :)

**Comment by llkats** [comment]
Cool, this was merged. Considering the amount of javascript that needs to be introduced to do favicon updating, I'm going to reopen #38 for further discussion.
