### ISSUE TITLE
us numbers with/without country code should resolve to same account

### ISSUE THREAD

**Issue by kelseyq** [bigboringsystem/bigboringsystem#53]
14155551212 and 4155551212 create two separate accounts now

**Comment by joates** [comment]
just FYI.. i am working on client-side validation in PR #130 

it encourages the use of '+1' but _does not_ enforce it..

server-side modules were suggested [here](https://github.com/bigboringsystem/bigboringsystem/issues/72#issuecomment-68853074)

**Comment by kelseyq** [comment]
thanks @joates--that'll help prevent new double accounts from being created. hoping to come up with an on-login merge to deal with old accounts w/o needing to take the db down. will have more updates later this week.

**Comment by ednapiranha** [comment]
@kelseyq I have an idea for migration which might be less headachey. Accounts can have secondary numbers added which reroute to the primary. We can just run something to add +1 and 1 accounts to primaries (or the first account of the three that exists that has a filled in profile name) // @isaacs

**Comment by isaacs** [comment]
As long as the existing number doesn't start with +1 or 1, then sure.

I feel like maybe we should just always cast to the international variant, if it doesn't have a +, and store that.

Adding secondary numbers as a migration technique sounds reasonable.

**Comment by ednapiranha** [comment]
yeah we could do either but i assume a lot of americans/canadians put stuff on their main account without using the +1 or 1

**Comment by cvan** [comment]
> I feel like maybe we should just always cast to the international variant, if it doesn't have a +, and store that.

+1 :+1:

**Comment by ednapiranha** [comment]
https://github.com/bigboringsystem/bigboringsystem/commit/49552c6e1c722e86be6803a9e3106ebe99a68869
