### ISSUE TITLE
Mutes and muffles

### ISSUE THREAD

**Issue by adambrault** [bigboringsystem/bigboringsystem#55]
While reading and thinking about #35, I realized as the community grows, it might be nice to be able to mute some posts and some people. Such mutes would only apply to your view of the discover area.

There are two cases I think would be useful and appropriate:
- hide a specific user's posts and chats.
- hide all replies to a specific post.

For muted users, I think the user should probably be 'disappeared' to you globally. I can imagine there are people who you'd want to see in chat but not see their posts (or vice versa), but that seems like over complicating the feature.

For muted replies, I could see the implementation being one of two ways:
- muted replies are not visible at all and cannot be viewed.
- the post is "muffled" and collapsed, with no content shown. So you could "see _x_ replied to _y_ muted post" and click in if you wanted to view it.

If the latter option were chosen (which I think is better), perhaps you "mute" users and "muffle" replies.

Adding this feature would also be beneficial and empowering to moderators, who could globally mute an abusive user to give them a timeout for bad behavior.

Opinions?

**Comment by isaacs** [comment]
I think we really need a "permanently block this user from my view, including their posts, replies to their posts, replies they post to posts of mine" and *maybe* also "keep them from seeing anything I post as well" but that's less important.

This really needs to be done server-side.

My experience with humans so far has been that once you give them the opportunity to be jerks, most will not, but a few will, and if you don't deliberately set things up to protect people from abuse, creeps will wield disproportionate power.

**Comment by isaacs** [comment]
Re impl, if we do it based on a user uid, then that blocks the abuser unless they get a new phone number, which is possible, but probably costly enough to not be an issue.  If they don't realize they're being blocked, then they're unlikely to even realize that they'd need to create another account.

On the other hand, the issue would be that they can delete their account and create a new one, I guess, and then they'd get a new uid with the same phone number...  If a creep *suspects* that they're getting blocked, then they can just keep doing this every day.  Maybe it'd be worthwhile to block based on phone number or IP?

**Comment by ednapiranha** [comment]
Currently setting up a PR for muting on chat only. The problem with muting on the post level (for now) is that we can miss offensive/inappropriate things that should be reported/deleted. Easy to add later if we need to but for now chat seems to be the biggest risk factor.

**Comment by ednapiranha** [comment]
If posts need to be muted, we should just assign this as a separate issue with a different behavior. Closing this one for now since the chat fix has been implemented.
