### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by TheAlphaNerd** [bigboringsystem/bigboringsystem#64]
Would people be interested in a CI system that could run tests + lint?

**Comment by rtorr** [comment]
+1

**Comment by TheAlphaNerd** [comment]
Basic Travis yaml has landed. Just need to get Travis configured with
proper env vars

**Comment by isaacs** [comment]
I flipped the switch on Travis-CI.  Not sure what else needs to happen, but I can take a look soon.  Probably the test env var stuff should just be part of #46, since we probably also want to make it so that new folks can try stuff out without needing a twilio account.

**Comment by TheAlphaNerd** [comment]
Making the env vars part of the test suite would be great, although I would
worry about making api keys public, seems open for abuse.

You can set env vars in the Travis config for the repo. I was able to get
it to work for my personal repo. Although I had to make sure that the
values that were strings were all wrapped in strings

**Comment by TheAlphaNerd** [comment]
Wrapped in quotes that is
