### ISSUE TITLE
can you provide details of the relationship with Twilio ?

### ISSUE THREAD

**Issue by joates** [bigboringsystem/bigboringsystem#83]
so the main question is..
by using this service am i exposing my device as a potential SMS marketing target to Twilio or any other company that they have partnered with ?

i'm just asking the question, it's not a "concern" of mine and i wouldn't be *too* bothered if that was a funding strategy, they provide a globally accessible infrastructure, they should get something for that i guess.

i looked on the Twilio.com website for details because i'm getting the login code SMS messages in London, UK and i'm not being charged for them (as far as i can tell) which is normal, but somebody must be paying for them to be sent.. i guess.

again.. this is not something that would prevent me from using this service i would just rather know to expect some SMS messages instead of them just start arriving (e.g. from Coca Cola or other companies) without any advance warning.

thanks :-)

**Comment by joates** [comment]
hmm, i just found this -> [sms pricing](https://www.twilio.com/sms/pricing)

**Comment by ednapiranha** [comment]
yeah i am :P

**Comment by urlysses** [comment]
i think a longer-lasting form of persistent login could help here with regards to $0.04/login. yesterday, i had to log in 3 or 4 different times from the same IP/browser though i never cleared my cookies.

**Comment by joates** [comment]
@urlysses 
just FYI.. i didn't really want to approach this as "login" issue, so IMO that discussion doesn't belong here (although that could be discussed in another issue : ). i actually like the use of SMS for authentication because we all, generally, have some personal investment in it.

i did however, as yourself, need to login several times (i think 3 actually) yesterday but that was mainly because i was getting familiar with the navigation (e.g. oh look a "log out" link, lets click that : )
now that i am aware of the cost incurred i can just login to post new content (perhaps as little as once a week).

also because i am located outside of US/Canada.. idk if it's less than $0.04 or free for US -> US numbers ? (there could be a viable case to regionalize but again, that's outside of scope for this issue)

**Comment by joates** [comment]
closing as the issue is resolved by this [response](https://github.com/bigboringsystem/bigboringsystem/issues/83#issuecomment-68495560)
