### ISSUE TITLE
profanity filter discussion.. (are curse words considered "offensive" ? which ones ?)

### ISSUE THREAD

**Issue by joates** [bigboringsystem/bigboringsystem#94]
is there a case for a profanity filter, something modular (probably already exists) ?

i *have* to ask because i am guilty of dropping 1 in only my 2nd post, it's something i don't do intentionally but i realise that it could be offensive.

without the ability to edit the post (which is fine, i actually like the *closure* that comes with that.. you hit the big red button to launch knowing that you can't change it after the fact -- although i could of course delete the whole thing, change 1 word and re-submit the censored version -- in fact i WILL do exactly that right now !)

**Comment by joates** [comment]
i should probably just stop cursing, that would be the easiest fix !!

please feel free to discuss the "profanity filter" suggestion

**Comment by joates** [comment]
quick search for [modules](https://www.npmjs.com/search?q=profanity)

**Comment by isaacs** [comment]
I think the best solution is to be able to mute/block specific users.  Then we can pretty much just let social mores work themselves out without anyone being abused.

In the short term, I think dropping a few f-bombs seems to be fine, as long as it's done in exuberance rather than hatred.

**Comment by jasonrhodes** [comment]
+1 for a user mute feature. If people are offended by usage of certain types of language across the site, it might be a good use-case for a "no potty mouth" bookmarklet or some such. But definitely something in "userland" :)

**Comment by joates** [comment]
while i'm not against it per-se muting is a *reactive* response, while profanity filtering on-the-fly sends a very clear message of intolerance (as in child-safe).

**Comment by amatecha** [comment]
but then: using non-alphanumeric characters to evade the filter

**Comment by isaacs** [comment]
The bbs community is, for the time being, naughty-word-friendly (but not hate-friendly, even if the hate is free of naughty words).  I think that profanity filtering is a tricky thing to do right, and probably bigboringsystem.com will never be 100% "child safe" for all varieties of what one might think is safe for a child.  (There's some *seriously heavy shit* getting posted occasionally there.  I wrote a post about the grief of dealing with a friend's suicide, ffs.)

If you were going to do this, I think the way forward would be to fork, and run it on your own server.  It could be a forcing function for a neat extension/plugin system, but it's unlikely to ever land in the main system except as a user-specific opt-in kinda deal.

**Comment by joates** [comment]
@amatecha good point, well made !
(you are correct, it's almost _impossible_ to implement, because there will always be newer and better evasion tactics)

@isaacs +1
(thanks for the detailed response, i agree, that would be the best way to handle the situation)

**Comment by joates** [comment]
closing this.

as @jasonrhodes suggested, can be resolved in "userland"
