### ISSUE TITLE
Needs a Privacy Policy

### ISSUE THREAD

**Issue by ednapiranha** [bigboringsystem/bigboringsystem#97]
Open to collaborating on this with @isaacs ?

Mainly - we will not sell your phone number or use it in nefarious ways, etc etc.

**Comment by urlysses** [comment]
If necessary, appdotnet provides a privacy policy template (and a ToS one as well).

https://github.com/appdotnet/template-terms-of-service/blob/master/privacy_template.md

Seems trivial to update the Use of Information section with relevant points.
